# Generated by Django 3.0.6 on 2020-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='dealers_cit_name_c4705a_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='dealers_cou_name_e099c0_idx'),
        ),
    ]
