# Generated by Django 3.0.6 on 2020-06-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='car',
        ),
    ]
