# Generated by Django 3.0.6 on 2020-06-10 17:34

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, unique=True)),
                ('last_name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, unique=True)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, choices=[('processed', 'Processed'), ('pend_pay', 'Pending payment'), ('paid', 'Paid'), ('archived', 'Archived')], default='processed', max_length=9)),
                ('car', models.ManyToManyField(related_name='orders', to='cars.Car')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_name', 'email'], name='orders_orde_last_na_5d8e9d_idx'),
        ),
    ]
