# Generated by Django 3.0.6 on 2020-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, unique=True)),
                ('last_name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(blank=True, choices=[('processed', 'processed'), ('pending_payment', 'pending_payment'), ('paid', 'paid'), ('archived', 'Archived')], default='processed', max_length=15)),
            ],
        ),
    ]
