# Generated by Django 3.0.6 on 2020-06-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_populate_colors'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ManyToManyField(to='cars.Car'),
        ),
    ]
