# Generated by Django 3.0.6 on 2020-06-09 14:46

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_name', 'phone'], name='orders_orde_last_na_1587a2_idx'),
        ),
    ]
