# Generated by Django 3.0.6 on 2020-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_dealer'),
        ('orders', '0003_auto_20200609_1446'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_last_na_1587a2_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ManyToManyField(related_name='orders', to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('pend_pay', 'Pending payment'), ('paid', 'Paid'), ('archived', 'Archived')], default='processed', max_length=9),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_name', 'email'], name='orders_orde_last_na_5d8e9d_idx'),
        ),
    ]
