# Generated by Django 3.0.6 on 2020-06-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200610_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('processed', 'Processed'), ('pend_pay', 'Pending payment'), ('paid', 'Paid'), ('archived', 'Archived')], default='processed', max_length=9),
        ),
    ]
