# Generated by Django 3.0.6 on 2020-06-09 13:54

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_populate_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('PL', 'Petrol engine'), ('DL', 'Diesel engine'), ('GS', 'Gaseous engine'), ('HB', 'Hybrid engine'), ('EC', 'Electric engine')], max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('PL', 'Petrol'), ('DL', 'Diesel'), ('GS', 'Gas'), ('HB', 'Hybrid'), ('EC', 'Electricity')], max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='gear_case',
            field=models.CharField(blank=True, choices=[('manual', 'Manual gear case'), ('automatic', 'Automatic gear case')], max_length=9),
        ),
        migrations.AddField(
            model_name='car',
            name='population_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=djmoney.models.fields.MoneyField(currency_choices=(('EUR', 'Euros'), ('USD', 'US Dollars'), ('UAH', 'Hryvnia')), decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('UAH', 'Hryvnia')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='car',
            name='sitting_place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('category', models.CharField(blank=True, max_length=25)),
                ('car', models.ManyToManyField(related_name='cars', to='cars.Car')),
            ],
        ),
    ]
