# Generated by Django 3.0.6 on 2020-06-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('cars', '0003_auto_20200609_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealers.Dealer'),
        ),
    ]
