# Generated by Django 3.0.6 on 2020-06-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('PL', 'Petrol engine'), ('DL', 'Diesel engine'), ('GS', 'Gaseous engine'), ('HB', 'Hybrid engine'), ('EC', 'Electric engine')], max_length=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PL', 'Petrol'), ('DL', 'Diesel'), ('GS', 'Gas'), ('HB', 'Hybrid'), ('EC', 'Electricity')], max_length=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_case',
            field=models.CharField(choices=[('manual', 'Manual gear case'), ('automatic', 'Automatic gear case')], max_length=9),
        ),
        migrations.AlterField(
            model_name='property',
            name='car',
            field=models.ManyToManyField(related_name='property', to='cars.Car'),
        ),
    ]
